create table entries (
	id int8 generated by default as identity primary key,
	time timestamp with time zone not null,
	level text not null,
	message text not null,
	labels jsonb null,
	metadata jsonb null
);
