create table entries (
	id int8 generated by default as identity primary key,
	time timestamp with time zone not null,
	stream_tag text not null,
	level text not null,
	message text not null,
	labels jsonb null,
	meta jsonb null,
	tx_id text null
);
