// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type Entry struct {
	ID          int64
	Time        int64
	Level       string
	Message     string
	Labels      sql.Null[[]byte]
	Meta        sql.Null[[]byte]
	TxID        sql.NullString
	ServiceName sql.NullString
}
