// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

type Entry struct {
	ID       int64
	Time     int64
	Level    string
	Message  string
	Labels   interface{}
	Metadata interface{}
}
