// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Entry struct {
	ID       int64
	Time     time.Time
	Level    string
	Message  string
	Labels   pqtype.NullRawMessage
	Metadata pqtype.NullRawMessage
}
