// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const insertEntry = `-- name: InsertEntry :exec
insert into entries (
	time,
	level,
	message,
	labels,
	meta,
	tx_id,
	stream_tag
) values (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
`

type InsertEntryParams struct {
	Time      time.Time
	Level     string
	Message   string
	Labels    sql.Null[[]byte]
	Meta      sql.Null[[]byte]
	TxID      sql.NullString
	StreamTag string
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry,
		arg.Time,
		arg.Level,
		arg.Message,
		arg.Labels,
		arg.Meta,
		arg.TxID,
		arg.StreamTag,
	)
	return err
}
